---

- hosts: kube_master
  become: true
  tasks:
    - set_fact: swiftETLNameSpace="dev"
      when: swiftETLNameSpace is undefined
    - set_fact: backup_path="/hostapp/backups/airflow"
      when: backup_path is undefined
    - name: Print Path where to store backup
      debug:
        msg: "Loading backup from {{backup_path}}"
        verbosity: 0
    - name: Get Persistent Volume
      shell: kubectl -n {{swiftETLNameSpace}} get PersistentVolumeClaim/data-airflow-{{swiftETLNameSpace}}-postgresql-0 -o jsonpath='{.spec.volumeName}'
      register: volume
    - name: Print Volume
      debug:
        msg: Volume is {{volume.stdout}}
    - name: Get Hostpath
      shell: kubectl -n {{swiftETLNameSpace}} get PersistentVolume/{{volume.stdout}} -o jsonpath='{.spec.hostPath.path}'
      register: hostpath
    - name: Print hostpath
      debug:
        msg: hostpath is {{hostpath.stdout}}
    - name: Copy Dump
      shell: cp {{backup_path}}/dump.sql {{hostpath.stdout}}/data/dump_in.sql 
    - name: Get postgres secret
      shell: kubectl -n {{swiftETLNameSpace}} get secrets/airflow-{{swiftETLNameSpace}}-postgresql -o jsonpath='{.data.postgresql-password}' | base64 -d
      register: pg_password
    - name: restore database
      shell: kubectl -n {{swiftETLNameSpace}} exec airflow-{{swiftETLNameSpace}}-postgresql-0 -- env PGPASSWORD="{{pg_password.stdout}}" psql -U postgres -w -f /bitnami/postgresql/data/dump_in.sql
    - name: (abort expected) Delete pods to restart airflow
      shell: kubectl -n {{swiftETLNameSpace}} delete pods -l release=airflow-{{swiftETLNameSpace}}
      async: 20
      poll: 5