---

- hosts: debians
  become: true
  roles:
    - { role: debian-basics }
    - { role: debian-docker }
    - { role: debian-grubconfig }
#    - { role: debian-kubernetes } disabled - because we will use k3s

- hosts: kube_master
  become: true
  roles:
    - { role: kube-master }

# kindoff hacky
# on the other hand - independence is broken at some point
- hosts: kube_master
  become: true
  tasks:
    - shell: cat /var/lib/rancher/k3s/server/token 
      register: kube_master_join_cmd
    - name: Create and print token
      shell: '{% raw %} kubectl -n kubernetes-dashboard describe secret admin-user-token | grep ^token {% endraw %}'
      register: token
    - name: Print Token to user
      debug:
        msg: "{{token.stdout}}"
        verbosity: 0
    - name: Copy Provisioning Scripts
      copy:
        src: ./library/provisioning
        dest: /root
    - name: make provision scripts executable
      shell: chmod u+x /root/provisioning/*.sh
    - name: install helm
      shell: /root/provisioning/install_helm.sh
    - name: install argo
      shell: /root/provisioning/install_argo.sh
    - name: open port for kubernetes-dashboard
      shell: /root/provisioning/port_dashboard.sh
    - name: Some Manual changes need to be done for server flags
      debug:
        msg: |
          Add the following lines to /etc/systemd/system/k3s.service
                  '--kube-apiserver-arg=enable-admission-plugins=NodeRestriction,PodNodeSelector' \
                  '--kube-proxy-arg=nodeport-addresses=192.168.0.0/16,127.0.0.0/8' \
                  '--kubelet-arg=feature-gates=NodeSwap=true' \
                  '--kubelet-arg=fail-swap-on=false' \
        verbosity: 0
    - name: Create ConfigMap for internal Namespace Names
      shell: kubectl create cm ns-lookup

- hosts: kube_slaves
  become: true
  roles:
    - { role: kube-slave }
