---

- hosts: debians
  become: true
  roles:
    - { role: debian-basics }
    - { role: debian-docker }
    - { role: debian-grubconfig }
#    - { role: debian-kubernetes } disabled - because we will use k3s

- hosts: kube_master
  become: true
  roles:
    - { role: kube-master }

# kindoff hacky
# on the other hand - independence is broken at some point
- hosts: kube_master
  become: true
  tasks:
    - shell: cat /var/lib/rancher/k3s/server/token 
      register: kube_master_join_cmd
    - name: Create and print token
      shell: '{% raw %} kubectl -n kubernetes-dashboard describe secret admin-user-token | grep ^token {% endraw %}'
      register: token
    - name: Print Token to user
      debug:
        msg: "{{token.stdout}}"
        verbosity: 0
    - name: Copy Provisioning Scripts
      copy:
        src: ./library/provisioning
        dest: /root
    - name: make provision scripts executable
      shell: chmod u+x /root/provisioning/*.sh
    - name: install helm
      shell: /root/provisioning/install_helm.sh
    - name: install argo
      shell: /root/provisioning/install_argo.sh
    - name: open port for kubernetes-dashboard
      shell: /root/provisioning/port_dashboard.sh

- hosts: kube_slaves
  become: true
  roles:
    - { role: kube-slave }
