---

- hosts: debians
  become: true
  roles:
    - { role: debian-basics }
    - { role: debian-docker }
    - { role: debian-grubconfig }
#    - { role: debian-kubernetes } disabled - because we will use k3s

- hosts: kube_master
  become: true
  roles:
    - { role: kube-master }

# kindoff hacky
# on the other hand - independence is broken at some point
- hosts: kube_master
  become: true
  tasks:
    - shell: cat /var/lib/rancher/k3s/server/token 
      register: kube_master_join_cmd

- hosts: kube_slaves
  become: true
  roles:
    - { role: kube-slave }
