
swiftETLNameSpace: dev
swiftETLAirflowPort: 30300
swiftETLDockerRegistryPort: 30500
swiftETLRepoURL: "https://github.com/apache/airflow.git"
gitSSHKey: SecretGitSSHKey=
gitKnownHostsOne: SecretGitKnownHostsOne
gitKnownHostsTwo: SecretGitKnownHostsTwo
