---

- name: Run apt-get update
  apt:
    update_cache: yes

- name: Run apt-get dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist


- name: Install commonly used packages
  apt:
    pkg:
      - iptables=1.8.7-1
      - ca-certificates=20210119
      - curl=7.74.0-1.3+deb11u1
      - gnupg=2.2.27-2+deb11u1
      - lsb-release=11.1.0
      - apt-transport-https=2.2.4