---

- name: Reset systemd cgroup handling to old mechanism, via kernel cmdline
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    state: absent
    line: GRUB_CMDLINE_LINUX=""
- name: Reset systemd cgroup handling to old mechanism, via kernel cmdline - step 2
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    state: present
    line: GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
- name: Update Grub
  ansible.builtin.shell: update-grub2

- name: Reboot Machines
  reboot:
