---

- name: Reenable plugin CRI
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    state: absent
    line: 'disabled_plugins = ["cri"]'

- name: Reenable plugin CRI part 2
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    state: present
    line: disabled_plugins = []

- name: Restart containerd
  shell: systemctl restart containerd

- name: create /root/.kube
  file:
    path: /root/.kube
    state: directory

- name: Create remote manifest directory
  file:
    path: /root/kube_manifests
    state: directory

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh -s - --docker --node-ip={{ansible_host}}

- name: Install Dashboard
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml

- name: Copy adminuser manifest
  ansible.builtin.copy:
    src: library/kube_manifests/dashboard-adminuser.yaml
    dest: /root/kube_manifests/dashboard-adminuser.yaml

- name: Copy ClusterRoleBinding manifest
  ansible.builtin.copy:
    src: library/kube_manifests/dashboard-adminuser-role-binding.yaml
    dest: /root/kube_manifests/dashboard-adminuser-role-binding.yaml

- name: Copy ClusterUser Token manifest
  ansible.builtin.copy:
    src: library/kube_manifests/dashboard-adminuser-token.yaml
    dest: /root/kube_manifests/dashboard-adminuser-token.yaml

- name: Apply adminuser manifest
  shell: kubectl apply -f /root/kube_manifests/dashboard-adminuser.yaml

- name: Apply ClusterRoleBinding manifest
  shell: kubectl apply -f /root/kube_manifests/dashboard-adminuser-role-binding.yaml

- name: Apply ClusterUser Token manifest
  shell: kubectl apply -f /root/kube_manifests/dashboard-adminuser-token.yaml

